### ISSUE TITLE
Tags not on new lines

### ISSUE THREAD

**Issue by scottiericho** [emmetio/Emmet.sugar#2]
When pressing control-E, new tags are only printed inline, one after the other, rather than formatted.

When changing the preferences, it crashes on close. But it DOES seem to save the preference to print on new lines - but it just doesn't work. 

Espresso 2.0.4. OS X 10.8.2.

**Comment by sergeche** [comment]
Just pushed update: should output correctly formatted HTML code

**Comment by scottiericho** [comment]
Many thanks for this. Downloading now. Will confirm if it works.

**Comment by scottiericho** [comment]
It works - many thanks for the quick update. :)
