### ISSUE TITLE
Not loading in Espresso 2.0.5?

### ISSUE THREAD

**Issue by scottiericho** [emmetio/Emmet.sugar#3]
Hi there,

I just tried to install Emmet into Espresso 2.0.5 but nothing happened. It doesn't appear in the Actions menu. Is this a known issue?

Scott

**Comment by sergeche** [comment]
Works for me. Can you open Console app and check if there are any errors when Espresso starts?

**Comment by scottiericho** [comment]
Just the following:

7/12/12 9:15:43.997 PM Espresso[25187]: Not including optional grammar with root zone sourcecode.js
7/12/12 9:15:43.997 PM Espresso[25187]: Not including optional grammar with root zone sourcecode.js
7/12/12 9:15:43.997 PM Espresso[25187]: Not including optional grammar with root zone sourcecode.js
7/12/12 9:15:43.998 PM Espresso[25187]: Not including optional grammar with root zone sourcecode.js
7/12/12 9:15:43.998 PM Espresso[25187]: Not including optional grammar with root zone sourcecode.js

**Comment by sergeche** [comment]
So, how did you installed this plugin? Can you post a screenshot of of Espresso’s Sugars folder content?

**Comment by scottiericho** [comment]
I tried it both ways - renaming and double clicking to install, and then when that didn't add anything to the Actions menu, I tried simply dragging the .sugar file to the correct folder. Screenshot coming... 

Worth noting, I just remembered having something similar happen the first time I tried to install Emmet on my mac Pro. Worked fine on my Air though.

**Comment by scottiericho** [comment]
http://www.scottrichardson.com.au/storage/screenshot.jpg

**Comment by sergeche** [comment]
That’s strange... Everything looks fine. Can you type `div` in your editor and hit <kbd>Ctrl+E</kbd>: does it transforms `div` to `<div></div>`?

**Comment by scottiericho** [comment]
No it doesn't do anything unfortunately :(

**Comment by sergeche** [comment]
The only way I can try to help you is if you give me access to your desktop. Can we do this via [TeamVewer](http://www.teamviewer.com)?

**Comment by scottiericho** [comment]
Certainly, I could download that, or use iChat/Messages with screen sharing?

**Comment by sergeche** [comment]
Yeah, let’s try with Messages. I never did so with Messages/iChat. I hope my GTalk account serge.che@gmail.com is enough?

**Comment by scottiericho** [comment]
I'm online now Sergey,

scottrichardson@mac.com is my iChat account :)

Scott

**Comment by sergeche** [comment]
I’ve updated README with better installation process description :)
